version: '2'
services:
  web:
    build: .
    image: garcianavalon/task3-web
    volumes:
     - ./python:/app
    depends_on:
     - redis
  redis:
    image: redis
  couchdb:
    image: klaemo/couchdb:2.0.0
    ports:
      - "5984:5984"
    volumes:
      - "/usr/local/var/lib/couchdb"
  lb:
    image: dockercloud/haproxy
    links:
      - web
    # For Docker Machine guys
    #environment:
    #  - DOCKER_HOST
    volumes:
      # For linux and Docker for Mac guys
      - /var/run/docker.sock:/var/run/docker.sock
  nginx:
    image: garcianavalon/task2-nginx
    volumes:
      - ./nginx/servers:/etc/nginx/servers
      - ./assets:/var/www/assets
      # OPTIONAL SSL
      # - ./path/to/certs:/etc/nginx/ssl
    links:
      - lb
      - couchdb
    ports:
      - "80:80"
      - "443:443"
