version: '2'
services:
  web:
    image: garcianavalon/task0-web
    depends_on:
     - redis
  redis:
    image: redis
  couchdb:
    image: klaemo/couchdb:2.0.0
    ports:
      - "5984:5984"
    volumes:
      - "/usr/local/var/lib/couchdb"
  lb:
    image: dockercloud/haproxy
    links:
      - web
    # For Docker Machine guys
    #environment:
    #  - DOCKER_HOST
    volumes:
      # For linux and Docker for Mac guys
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "6767:80"
