version: '2'
services:
  web:
    image: garcianavalon/task0-web
    depends_on:
     - redis
  redis:
    image: redis
  couchdb:
    image: klaemo/couchdb:2.0.0
    ports:
      - "5984:5984"
    volumes:
      - "/usr/local/var/lib/couchdb"
  lb:
    image: dockercloud/haproxy
    links:
      - web
    # For Docker Machine guys
    #environment:
    #  - DOCKER_HOST
    volumes:
      # For linux and Docker for Mac guys
      - /var/run/docker.sock:/var/run/docker.sock
  nginx:
    image: nginx:1.10
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/servers:/etc/nginx/servers
      # OPTIONAL SSL
      # - ./path/to/certs:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
