version: '2'
services:
  web:
    image: garcianavalon/task0-web
    depends_on:
     - redis
  redis:
    image: redis
  lb:
    image: dockercloud/haproxy
    links:
      - web
    # For Docker Machine guys
    #environment:
    #  - DOCKER_HOST
    volumes:
      # For linux and Docker for Mac guys
      - /var/run/docker.sock:/var/run/docker.sock
  nginx:
    build: .
    image: garcianavalon/task2-nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/servers:/etc/nginx/servers
      # OPTIONAL SSL
      # - ./path/to/certs:/etc/nginx/ssl
    links:
      - lb
    ports:
      - "80:80"
      - "443:443"
